"""

Revision ID: 0872b9536101
Revises: a3f50114e186
Create Date: 2020-03-01 01:55:14.505823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0872b9536101'
down_revision = 'a3f50114e186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###