"""

Revision ID: a3f50114e186
Revises: 
Create Date: 2020-03-01 00:23:00.179129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f50114e186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'join_filter')
    op.drop_column('chats', 'is_official')
    op.drop_column('chats', 'language')
    op.drop_column('chats', 'is_vip')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'do_not_disturb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('do_not_disturb', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('is_vip', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('language', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('is_official', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('join_filter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###